Document: tabletclient-lehrer
Title: Debian tabletclient-lehrer Manual
Author: <insert document author here>
Abstract: This manual describes what tabletclient-lehrer is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/tabletclient-lehrer/tabletclient-lehrer.sgml.gz

Format: postscript
Files: /usr/share/doc/tabletclient-lehrer/tabletclient-lehrer.ps.gz

Format: text
Files: /usr/share/doc/tabletclient-lehrer/tabletclient-lehrer.text.gz

Format: HTML
Index: /usr/share/doc/tabletclient-lehrer/html/index.html
Files: /usr/share/doc/tabletclient-lehrer/html/*.html
