Document: gbglehrerclient
Title: Debian gbglehrerclient Manual
Author: <insert document author here>
Abstract: This manual describes what gbglehrerclient is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gbglehrerclient/gbglehrerclient.sgml.gz

Format: postscript
Files: /usr/share/doc/gbglehrerclient/gbglehrerclient.ps.gz

Format: text
Files: /usr/share/doc/gbglehrerclient/gbglehrerclient.text.gz

Format: HTML
Index: /usr/share/doc/gbglehrerclient/html/index.html
Files: /usr/share/doc/gbglehrerclient/html/*.html
