Document: gbgclient
Title: Debian gbgclient Manual
Author: <insert document author here>
Abstract: This manual describes what gbgclient is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gbgclient/gbgclient.sgml.gz

Format: postscript
Files: /usr/share/doc/gbgclient/gbgclient.ps.gz

Format: text
Files: /usr/share/doc/gbgclient/gbgclient.text.gz

Format: HTML
Index: /usr/share/doc/gbgclient/html/index.html
Files: /usr/share/doc/gbgclient/html/*.html
