Document: gbgclient-edge
Title: Debian gbgclient-edge Manual
Author: <insert document author here>
Abstract: This manual describes what gbgclient-edge is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gbgclient-edge/gbgclient-edge.sgml.gz

Format: postscript
Files: /usr/share/doc/gbgclient-edge/gbgclient-edge.ps.gz

Format: text
Files: /usr/share/doc/gbgclient-edge/gbgclient-edge.text.gz

Format: HTML
Index: /usr/share/doc/gbgclient-edge/html/index.html
Files: /usr/share/doc/gbgclient-edge/html/*.html
