Document: dateiablage
Title: Debian dateiablage Manual
Author: <insert document author here>
Abstract: This manual describes what dateiablage is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dateiablage/dateiablage.sgml.gz

Format: postscript
Files: /usr/share/doc/dateiablage/dateiablage.ps.gz

Format: text
Files: /usr/share/doc/dateiablage/dateiablage.text.gz

Format: HTML
Index: /usr/share/doc/dateiablage/html/index.html
Files: /usr/share/doc/dateiablage/html/*.html
