Document: convertibleclient-lehrer
Title: Debian convertibleclient-lehrer Manual
Author: <insert document author here>
Abstract: This manual describes what convertibleclient-lehrer is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/convertibleclient-lehrer/convertibleclient-lehrer.sgml.gz

Format: postscript
Files: /usr/share/doc/convertibleclient-lehrer/convertibleclient-lehrer.ps.gz

Format: text
Files: /usr/share/doc/convertibleclient-lehrer/convertibleclient-lehrer.text.gz

Format: HTML
Index: /usr/share/doc/convertibleclient-lehrer/html/index.html
Files: /usr/share/doc/convertibleclient-lehrer/html/*.html
