Document: gbgclient-hirsute
Title: Debian gbgclient-hirsute Manual
Author: <insert document author here>
Abstract: This manual describes what gbgclient-hirsute is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gbgclient-hirsute/gbgclient-hirsute.sgml.gz

Format: postscript
Files: /usr/share/doc/gbgclient-hirsute/gbgclient-hirsute.ps.gz

Format: text
Files: /usr/share/doc/gbgclient-hirsute/gbgclient-hirsute.text.gz

Format: HTML
Index: /usr/share/doc/gbgclient-hirsute/html/index.html
Files: /usr/share/doc/gbgclient-hirsute/html/*.html
