Document: gbglehrer-testclient3
Title: Debian gbglehrer-testclient3 Manual
Author: <insert document author here>
Abstract: This manual describes what gbglehrer-testclient3 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gbglehrer-testclient3/gbglehrer-testclient3.sgml.gz

Format: postscript
Files: /usr/share/doc/gbglehrer-testclient3/gbglehrer-testclient3.ps.gz

Format: text
Files: /usr/share/doc/gbglehrer-testclient3/gbglehrer-testclient3.text.gz

Format: HTML
Index: /usr/share/doc/gbglehrer-testclient3/html/index.html
Files: /usr/share/doc/gbglehrer-testclient3/html/*.html
