Document: gbgpersonalclient
Title: Debian gbgpersonalclient Manual
Author: <insert document author here>
Abstract: This manual describes what gbgpersonalclient is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gbgpersonalclient/gbgpersonalclient.sgml.gz

Format: postscript
Files: /usr/share/doc/gbgpersonalclient/gbgpersonalclient.ps.gz

Format: text
Files: /usr/share/doc/gbgpersonalclient/gbgpersonalclient.text.gz

Format: HTML
Index: /usr/share/doc/gbgpersonalclient/html/index.html
Files: /usr/share/doc/gbgpersonalclient/html/*.html
