Document: gbgsusclient
Title: Debian gbgsusclient Manual
Author: <insert document author here>
Abstract: This manual describes what gbgsusclient is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gbgsusclient/gbgsusclient.sgml.gz

Format: postscript
Files: /usr/share/doc/gbgsusclient/gbgsusclient.ps.gz

Format: text
Files: /usr/share/doc/gbgsusclient/gbgsusclient.text.gz

Format: HTML
Index: /usr/share/doc/gbgsusclient/html/index.html
Files: /usr/share/doc/gbgsusclient/html/*.html
