#!/bin/sh
#/etc/gdm3/PostLogin/Default
guestuser="gbg" ## Next set up guest user session files/folders
if [[ "$USER" = "$guestuser" ]]; then
   mkdir /tmp/"$guestuser"
   cp /etc/skel/* /tmp/"$guestuser"
   chown -R "$guestuser":"$guestuser" /tmp/"$guestuser"
fi
exit 0
