Document: gbglehrerclient2
Title: Debian gbglehrerclient2 Manual
Author: <insert document author here>
Abstract: This manual describes what gbglehrerclient2 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gbglehrerclient2/gbglehrerclient2.sgml.gz

Format: postscript
Files: /usr/share/doc/gbglehrerclient2/gbglehrerclient2.ps.gz

Format: text
Files: /usr/share/doc/gbglehrerclient2/gbglehrerclient2.text.gz

Format: HTML
Index: /usr/share/doc/gbglehrerclient2/html/index.html
Files: /usr/share/doc/gbglehrerclient2/html/*.html
