Document: gbglzclient
Title: Debian gbglzclient Manual
Author: <insert document author here>
Abstract: This manual describes what gbglzclient is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gbglzclient/gbglzclient.sgml.gz

Format: postscript
Files: /usr/share/doc/gbglzclient/gbglzclient.ps.gz

Format: text
Files: /usr/share/doc/gbglzclient/gbglzclient.text.gz

Format: HTML
Index: /usr/share/doc/gbglzclient/html/index.html
Files: /usr/share/doc/gbglzclient/html/*.html
